name: "Slack Message Scheduler"
description: "Schedules messages from the files specified in message-file"
inputs:
  slack-user-oauth-access-token:
    description: "User OAuth access token, or alternative a json with user-names as keys and their tokens as values"
    required: true
  message-file:
    description: "File with messages to be send, seperate multiple files with ;"
    required: true
  slack-workspace-id:
    description: "If provided it checks the given user tokens if they are from the workspace id"
    required: false
runs:
  using: "node12"  
  main: "index.js"
